---
title: "EMadin Module"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Upload data

```{r}
data = read.csv('groupdata.csv')

head(data)

data import, echo=TRUE, results='hide', include=FALSE}
################################################
# import data, observe structure
################################################
data<-read.csv("data/Module1_MeasuringReefs_EM.csv", header = TRUE)
names(data)
head(data)
data$year<-substr(data$date,0,4) # add a column for year only
```


```{r data explore-1, echo=TRUE, results='hide', fig.height=5, fig.width=5, fig.align='center'}
################################################
# explore patterns
################################################
# Effect of method
plot(area_m2~method, data=data, na.ignore=TRUE, col="lightgrey",
     ylab="Patch reef area (m^2)", 
     xlab="Method", 
     main="Area versus method")
dev.copy(pdf,"figs/method_area_effect.pdf")    # can change to .png, etc.; can change size to incr resolution
dev.off()
# Effect of imagery resolution
plot(area_m2~imagery_resolution_m, data=data, col="slategrey",
     xlim=c(0,10),
     xlab="Imagery spatial resolution (m)", 
     ylab="Patch reef area (m^2)", 
     main="Area versus imagery resolution")
res.area.lm=lm(area_m2 ~ imagery_resolution_m, data=data)
abline(res.area.lm, col = "black")
summary(res.area.lm)
dev.copy(pdf,"figs/resolution_area_effect.pdf")    
dev.off()
plot(perimeter_m~imagery_resolution_m, data=data, col="slategrey",
     xlim=c(0,10),
     xlab="Imagery spatial resolution (m)", 
     ylab="Patch reef perimeter (m)", 
     main="Perimeter versus imagery resolution")
res.perim.lm=lm(perimeter_m ~ imagery_resolution_m, data=data)
abline(res.perim.lm, col = "black")
summary(res.perim.lm)
dev.copy(pdf,"figs/resolution_perimeter_effect.pdf")    
dev.off()
# Effect of date (i.e., do patch reefs measureably grow or shrink over time?)
plot(area_m2~as.numeric(year), data=data, col="slategrey",
     xlab="Year", 
     ylab="Patch reef area (m^2)", 
     main="Area versus year")
date.area.lm=lm(area_m2 ~ as.numeric(year), data=data)
abline(date.area.lm, col = "black")
summary(date.area.lm)
dev.copy(pdf,"figs/date_area_effect.pdf")    
dev.off()


```

# Introduction
# Methods
# Results

```{r data analysis-1, echo=TRUE, results='hide', fig.height=5, fig.width=5, fig.align='center'}
################################################
# analyze data
################################################
# Effects of imagery resolution + year

data$year<-substr(data$date,0,4)

res.year.lm=lm(area_m2 ~ imagery_resolution_m * as.numeric(year), data=data)
summary(res.year.lm)
```

Or reef identity (number):

```{r data analysis-2, echo=TRUE, results='hide', fig.height=5, fig.width=5, fig.align='center'}
################################################
# analyze data
################################################
# Effects of imagery resolution + reef ID
res.reefID.lm=lm(area_m2 ~ imagery_resolution_m * reef_no, data=data)
summary(res.reefID.lm)

```


# Discussion


